/* The following code was generated by JFlex 1.7.0 */

/***************************/
/* FILE NAME: LEX_FILE.lex */
/***************************/

/*************/
/* USER CODE */
/*************/
import java_cup.runtime.*;

/******************************/
/* DOLLAR DOLLAR - DON'T TOUCH! */
/******************************/

class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\55\1\55\1\1\22\0\1\3\1\10\1\7"+
    "\1\0\1\0\3\0\1\44\1\45\1\12\1\42\1\52\1\43\1\53"+
    "\1\11\1\4\11\5\1\36\1\54\1\40\1\37\1\41\1\10\1\0"+
    "\32\6\1\46\1\0\1\47\3\0\1\15\1\6\1\13\1\31\1\25"+
    "\1\26\1\33\1\24\1\20\2\6\1\14\1\6\1\17\1\35\2\6"+
    "\1\21\1\16\1\30\1\32\1\34\1\23\1\27\1\22\1\6\1\50"+
    "\1\0\1\51\7\0\1\55\u1fa2\0\1\55\1\55\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\1\1\5\1\6"+
    "\11\4\1\1\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\0\1\26\1\27\1\30\6\4\1\31\5\4"+
    "\1\32\2\0\3\4\1\33\1\34\1\35\5\4\1\36"+
    "\5\4\1\37\1\4\1\40\1\41\1\42\2\4\1\43"+
    "\1\4\1\44\1\45\1\4\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\212\0\270\0\346\0\u0114"+
    "\0\u0142\0\56\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\u030e\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\212\0\u0114\0\56\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\346\0\u04ac\0\u04da"+
    "\0\u0508\0\u0536\0\u0564\0\56\0\u036a\0\u0592\0\u05c0\0\u05ee"+
    "\0\u061c\0\346\0\346\0\346\0\u064a\0\u0678\0\u06a6\0\u06d4"+
    "\0\u0702\0\u036a\0\u0730\0\u075e\0\u078c\0\u07ba\0\u07e8\0\346"+
    "\0\u0816\0\346\0\346\0\346\0\u0844\0\u0872\0\346\0\u08a0"+
    "\0\346\0\346\0\u08ce\0\346";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\11\1\12\1\13\1\7\1\14\1\15\1\16\1\17"+
    "\1\20\1\7\1\21\1\7\1\22\6\7\1\23\1\7"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\61\0"+
    "\1\4\57\0\2\43\54\0\2\6\54\0\3\7\4\0"+
    "\23\7\26\0\1\44\1\45\3\0\23\44\31\0\1\46"+
    "\1\47\47\0\3\7\4\0\1\7\1\50\21\7\24\0"+
    "\3\7\4\0\6\7\1\51\14\7\24\0\3\7\4\0"+
    "\15\7\1\52\5\7\24\0\3\7\4\0\5\7\1\53"+
    "\4\7\1\54\10\7\24\0\3\7\4\0\4\7\1\55"+
    "\6\7\1\56\7\7\24\0\3\7\4\0\12\7\1\57"+
    "\10\7\24\0\3\7\4\0\11\7\1\60\11\7\24\0"+
    "\3\7\4\0\1\7\1\61\12\7\1\62\6\7\24\0"+
    "\3\7\4\0\22\7\1\63\57\0\1\64\21\0\4\46"+
    "\1\0\26\46\4\0\10\46\1\0\2\46\2\0\6\65"+
    "\1\0\2\65\1\66\23\65\4\0\10\65\1\0\2\65"+
    "\5\0\3\7\4\0\2\7\1\67\20\7\24\0\3\7"+
    "\4\0\6\7\1\70\14\7\24\0\3\7\4\0\6\7"+
    "\1\71\14\7\24\0\3\7\4\0\1\7\1\72\21\7"+
    "\24\0\3\7\4\0\10\7\1\73\12\7\24\0\3\7"+
    "\4\0\15\7\1\74\5\7\24\0\3\7\4\0\15\7"+
    "\1\75\5\7\24\0\3\7\4\0\5\7\1\76\15\7"+
    "\24\0\3\7\4\0\3\7\1\77\17\7\24\0\3\7"+
    "\4\0\15\7\1\100\5\7\24\0\3\7\4\0\5\7"+
    "\1\101\15\7\21\0\6\65\1\0\1\65\1\102\1\66"+
    "\23\65\4\0\10\65\1\0\2\65\5\0\3\7\4\0"+
    "\3\7\1\103\17\7\24\0\3\7\4\0\2\7\1\104"+
    "\20\7\24\0\3\7\4\0\5\7\1\105\15\7\24\0"+
    "\3\7\4\0\17\7\1\106\3\7\24\0\3\7\4\0"+
    "\1\7\1\107\21\7\24\0\3\7\4\0\12\7\1\110"+
    "\10\7\24\0\3\7\4\0\12\7\1\111\10\7\24\0"+
    "\3\7\4\0\16\7\1\112\4\7\24\0\3\7\4\0"+
    "\3\7\1\113\17\7\24\0\3\7\4\0\7\7\1\114"+
    "\13\7\24\0\3\7\4\0\4\7\1\115\16\7\24\0"+
    "\3\7\4\0\6\7\1\116\14\7\24\0\3\7\4\0"+
    "\12\7\1\117\10\7\24\0\3\7\4\0\4\7\1\120"+
    "\16\7\24\0\3\7\4\0\20\7\1\121\2\7\24\0"+
    "\3\7\4\0\4\7\1\122\16\7\24\0\3\7\4\0"+
    "\16\7\1\123\4\7\24\0\3\7\4\0\3\7\1\124"+
    "\17\7\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\5\1\1\11\12\1\16\11"+
    "\1\1\1\0\1\11\16\1\1\11\2\0\36\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[84];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /*********************************************************************************/
    /* Create a new java_cup.runtime.Symbol with information about the current token */
    /*********************************************************************************/
    private Symbol symbol(int type)               { return new Symbol(type, yyline, yycolumn); }
    private Symbol symbol(int type, Object value) { return new Symbol(type, yyline, yycolumn, value); }

    /*******************************************/
    /* Enable line number extraction from main */
    /*******************************************/
    public int getLine() { return yyline + 1; }

    /**********************************************/
    /* Enable token position extraction from main */
    /**********************************************/
    public int getTokenStartPosition() { return yycolumn + 1; }

    /*******************************************/
    /* DEBUG PRINT HELPER                      */
    /*******************************************/
    private void debug(String tokenName) {
        System.err.println("LEXER DEBUG: Matched " + tokenName + " '" + yytext() +
                           "' (Line " + getLine() + ", Col " + getTokenStartPosition() + ")");
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(TokenNames.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { debug("CATCH-ALL (NO MATCH)"); throw new RuntimeException("LEX_ERROR");
            } 
            // fall through
          case 39: break;
          case 2: 
            { debug("WhiteSpace (Skipped)"); /* skip */
            } 
            // fall through
          case 40: break;
          case 3: 
            { try {
            debug("INT (Pre-check)");
            int val = Integer.parseInt(yytext());
            if (val < 0 || val > 32767) {
                debug("INT (Out of Range)");
                throw new NumberFormatException("Value exceeds L language limit");
            }
            return symbol(TokenNames.INT, Integer.valueOf(val));
        } catch (NumberFormatException e) {
            throw new RuntimeException("LEX_ERROR");
        }
            } 
            // fall through
          case 41: break;
          case 4: 
            { debug("ID");
        return symbol(TokenNames.ID, yytext());
            } 
            // fall through
          case 42: break;
          case 5: 
            { debug("DIVIDE");  return symbol(TokenNames.DIVIDE);
            } 
            // fall through
          case 43: break;
          case 6: 
            { debug("TIMES");   return symbol(TokenNames.TIMES);
            } 
            // fall through
          case 44: break;
          case 7: 
            { debug("EQ");      return symbol(TokenNames.EQ);
            } 
            // fall through
          case 45: break;
          case 8: 
            { debug("LT");      return symbol(TokenNames.LT);
            } 
            // fall through
          case 46: break;
          case 9: 
            { debug("GT");      return symbol(TokenNames.GT);
            } 
            // fall through
          case 47: break;
          case 10: 
            { debug("PLUS");    return symbol(TokenNames.PLUS);
            } 
            // fall through
          case 48: break;
          case 11: 
            { debug("MINUS");   return symbol(TokenNames.MINUS);
            } 
            // fall through
          case 49: break;
          case 12: 
            { debug("LPAREN");    return symbol(TokenNames.LPAREN);
            } 
            // fall through
          case 50: break;
          case 13: 
            { debug("RPAREN");    return symbol(TokenNames.RPAREN);
            } 
            // fall through
          case 51: break;
          case 14: 
            { debug("LBRACK");    return symbol(TokenNames.LBRACK);
            } 
            // fall through
          case 52: break;
          case 15: 
            { debug("RBRACK");    return symbol(TokenNames.RBRACK);
            } 
            // fall through
          case 53: break;
          case 16: 
            { debug("LBRACE");    return symbol(TokenNames.LBRACE);
            } 
            // fall through
          case 54: break;
          case 17: 
            { debug("RBRACE");    return symbol(TokenNames.RBRACE);
            } 
            // fall through
          case 55: break;
          case 18: 
            { debug("COMMA");     return symbol(TokenNames.COMMA);
            } 
            // fall through
          case 56: break;
          case 19: 
            { debug("DOT");       return symbol(TokenNames.DOT);
            } 
            // fall through
          case 57: break;
          case 20: 
            { debug("SEMICOLON"); return symbol(TokenNames.SEMICOLON);
            } 
            // fall through
          case 58: break;
          case 21: 
            { debug("INVALID_NUMBER"); throw new RuntimeException("LEX_ERROR");
            } 
            // fall through
          case 59: break;
          case 22: 
            { debug("STRING");
        return symbol(TokenNames.STRING, yytext());
            } 
            // fall through
          case 60: break;
          case 23: 
            { debug("LINE_COMMENT (Skipped)");  /* skip */
            } 
            // fall through
          case 61: break;
          case 24: 
            { debug("INVALID COMMENT (Partial Block)"); throw new RuntimeException("LEX_ERROR");
            } 
            // fall through
          case 62: break;
          case 25: 
            { debug("IF");       return symbol(TokenNames.IF);
            } 
            // fall through
          case 63: break;
          case 26: 
            { debug("ASSIGN");  return symbol(TokenNames.ASSIGN);
            } 
            // fall through
          case 64: break;
          case 27: 
            { debug("NIL");      return symbol(TokenNames.NIL);
            } 
            // fall through
          case 65: break;
          case 28: 
            { debug("NEW");      return symbol(TokenNames.NEW);
            } 
            // fall through
          case 66: break;
          case 29: 
            { debug("TYPE_INT"); return symbol(TokenNames.TYPE_INT);
            } 
            // fall through
          case 67: break;
          case 30: 
            { debug("BLOCK_COMMENT (Skipped)"); /* skip */
            } 
            // fall through
          case 68: break;
          case 31: 
            { debug("ELSE");     return symbol(TokenNames.ELSE);
            } 
            // fall through
          case 69: break;
          case 32: 
            { debug("TYPE_VOID");   return symbol(TokenNames.TYPE_VOID);
            } 
            // fall through
          case 70: break;
          case 33: 
            { debug("CLASS");    return symbol(TokenNames.CLASS);
            } 
            // fall through
          case 71: break;
          case 34: 
            { debug("ARRAY");    return symbol(TokenNames.ARRAY);
            } 
            // fall through
          case 72: break;
          case 35: 
            { debug("WHILE");    return symbol(TokenNames.WHILE);
            } 
            // fall through
          case 73: break;
          case 36: 
            { debug("TYPE_STRING"); return symbol(TokenNames.TYPE_STRING);
            } 
            // fall through
          case 74: break;
          case 37: 
            { debug("RETURN");   return symbol(TokenNames.RETURN);
            } 
            // fall through
          case 75: break;
          case 38: 
            { debug("EXTENDS");  return symbol(TokenNames.EXTENDS);
            } 
            // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
